name: JoinManager
main: com.fornow_blog.joinmanager.JoinManager
version: 0.0.1
authors: [yuto0513, togtog]
permissions:
  joinmanager.*:
    description: Gives access to all joinmanager commands.
commands:
  jm:
    description: This is commands of JoinManager.
    usage: /<command> help
    permission: joinmanager.help
    permission-message: You do not have <permission>.
